### ISSUE TITLE
Implement SSL strategies

### ISSUE THREAD

**Issue by rusuly** [rusuly/MySqlCdc#7]
BinlogClient should support the following SSL strategies:

1. None
2. If available
3. Require
4. Require and verify CA
5. Require and verify Identity

**Comment by wangengzheng** [comment]
Hi rusuly, this looks really good, I had this problem.

I upgraded the nuget package of dotnet6 (MysqlCdc --version 3.0.1) to connect past azure mysql database. prompt error.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySqlCdc.Extensions.ThrowIfErrorPacket(Byte[] packet, String message)
   at MySqlCdc.Connector.AuthenticateAsync(HandshakePacket handshake, Byte seqNum, CancellationToken cancellationToken)
   at MySqlCdc.Connector.ConnectAsync(CancellationToken cancellationToken)
   at MySqlCdc.BinlogClient.Replicate(CancellationToken cancellationToken)+MoveNext()
   at MySqlCdc.BinlogClient.Replicate(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```
  
ThrowIfErrorPacket method received empty array. The message prompt is Authentication error.

I lowered the mysqlcdc nuget to the corresponding 2.0.1 under the dotnet6 framework and it worked normally.



_Limitations_
- **Currently, the library doesn't fully support SSL encryption.** <------Is it related?

**Comment by rusuly** [comment]
Hi, sorry for late response.
I think it's just a bug in 3.0.1 and it's not related to SSL statement in the docs.
Unfortunately, I cannot maintain the respository now so I hope you will manage to debug and fix the issue if you need exactly 3.0.1 version.

**Comment by wangengzheng** [comment]
thax
